language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - "/^v?[0-9\\.]+$/"

php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'

before_script:
  - composer install

script:
  - composer test
