name: CI/CD for PHP Library

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]  # OS. ubuntu-18.04 is also available.
        php: [ '7.4', '8.0', '8.1' ] # PHP versions to check.
        wp: [ '5.9', 'latest' ]
        tools: [ composer ]
        include:
          - os: ubuntu-18.04
            php: 5.6
            tools: composer:v2.2
            wp: 5.9
          - os: ubuntu-18.04
            php: 5.6
            tools: composer:v2.2
            wp: latest
    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd "mysqladmin ping --host 127.0.0.1 --port 3306" --health-interval 20s --health-timeout 10s --health-retries 10
        ports:
          - 3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: root
    runs-on: ${{ matrix.os }}
    name: UnitTest in WordPress ${{ matrix.wp }} and PHP ${{ matrix.php }}
    steps:
      - uses: actions/checkout@master

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: ${{ matrix.tools }}

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check PHP syntax
        run: composer lint

      - name: Start MySQL
        run: sudo systemctl start mysql
        if: matrix.php != 5.6

      - name: Install WordPress
        run: bash bin/install-wp-tests.sh wordpress root root 127.0.0.1:3306 ${{ matrix.wp }}
        if: matrix.php != 5.6

      - name: Unit Test
        run: composer test
        if: matrix.php != 5.6

  release:
    name: Create Release Package
    needs: [ test ]
    if: contains(github.ref, 'tags/')
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 5.6
          tools: composer:v2.2

      - name: Clean Package
        run: bash bin/cleanup.sh

      - name: Zip Archive
        run: zip -r ${{ github.event.repository.name }}.zip ./

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/${{ github.event.repository.name }}.zip
          asset_name: ${{ github.event.repository.name }}.zip
          asset_content_type: application/zip
